/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes } = useGLTF('/pokemonGLB/Alakazam.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.foodin.geometry} material={nodes.foodin.material} position={[0,3,0]} scale={[4,4,4]}/>
    </group>
  )
}

useGLTF.preload('/pokemonGLB/Alakazam.glb')
