/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes } = useGLTF('/pokemonGLB/Error.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_E'].geometry}
        material={nodes['3D_Text_-_E'].material}
        position={[-30, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_r_1'].geometry}
        material={nodes['3D_Text_-_r_1'].material}
        position={[-25, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_r_2'].geometry}
        material={nodes['3D_Text_-_r_2'].material}
        position={[-21, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_r'].geometry}
        material={nodes['3D_Text_-_r'].material}
        position={[-12, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_o_1'].geometry}
        material={nodes['3D_Text_-_o_1'].material}
        position={[-17.5, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_o'].geometry}
        material={nodes['3D_Text_-_o'].material}
        position={[1, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_'].geometry}
        material={nodes['3D_Text_-_'].material}
        position={[-20, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_N'].geometry}
        material={nodes['3D_Text_-_N'].material}
        position={[-5, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_t'].geometry}
        material={nodes['3D_Text_-_t'].material}
        position={[6, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_V'].geometry}
        material={nodes['3D_Text_-_V'].material}
        position={[14, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_a'].geometry}
        material={nodes['3D_Text_-_a'].material}
        position={[19, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_l'].geometry}
        material={nodes['3D_Text_-_l'].material}
        position={[24, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_i'].geometry}
        material={nodes['3D_Text_-_i'].material}
        position={[27, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        castShadow
        geometry={nodes['3D_Text_-_d'].geometry}
        material={nodes['3D_Text_-_d'].material}
        position={[30, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />
    </group>
  )
}

useGLTF.preload('/pokemon/Error.glb')
