/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes } = useGLTF('/pokemonGLB/Grimer.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.betbeter.geometry} material={nodes.betbeter.material} scale={[3,3,3]} position={[0,5,0]}/>
    </group>
  )
}

useGLTF.preload('/pokemonGLB/Grimer.glb')
