/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes} = useGLTF('/pokemonGLB/Luffy.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Plane01.geometry} material={nodes.Plane01.material} scale={0.2} position={[0,0,7]}/>
    </group>
  )
}

useGLTF.preload('/pokemonGLB/Luffy.glb')
