/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes } = useGLTF('/pokemonGLB/Mew.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Mew.geometry} material={nodes.Mew.material} scale={[0.4,0.4,0.4]}/>
    </group>
  )
}

useGLTF.preload('/pokemonGLB/Mew.glb')
