/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/pokemonGLB/Nidoking.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Nidoking.geometry} material={nodes.Nidoking.material} scale={[0.1,0.1,0.1]}/>
    </group>
  )
}

useGLTF.preload('/pokemonGLB/Nidoking.glb')
