/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes } = useGLTF(
    '/pokemonGLB/Sandshrew.glb'
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.sand.geometry} material={nodes.sand.material} position={[0,3,0]}/>
    </group>
  )
}

useGLTF.preload('/pokemonGLB/Sandshrew.glb')
